### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by brendonakay**
Hey Justin - Here's my changes for problem #19 ... I believe the 3+ thousand files changed is due to me operating on a Mac and the original source being on Linux. 

http://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important

I only updated the two files in  climbmapper/public/data/

Also, bak04280 is an old account I had from my college days. I updated my .gitconfig so the account is brendonakay.

### CODE REVIEW

**Comment by brendonakay** [comment]
It was a little late for me last night. Let me know if you'd like me to submit new commits.

**Comment by justinlewis** [comment]
​Ha!  Ya, I've seen that line break issue before.  It looks like most, if
not all, of the file changes are in the node_modules files which I should
have never committed in the ​first place.  In more recent major Node
versions you're supposed to exclude that directory from Git because Node
will just re-build those dependency files for each project.  I haven't
pulled the pull request yet but I'll look into a way to maybe get around
it...


*Justin Lewis*

*J.mapping@Gmail.com**(360) 303-8930*
<http://www.linkedin.com/pub/justin-lewis/b/b94/861/>

**Comment by brendonakay** [comment]
lol yah sry about that mess. I completely reset my fork if you want me to submit a new (cleaner) pull request.

**Comment by justinlewis** [comment]
I removed the node_modules from the reactify branch a bit ago but haven't merged it with master or dev.  However, i just added the appropriate .gitignore and deleted the node_modules dir from the dev branch.  can you try doing a pull and checking if your node module directory is then excluded from your Git index?  You may have to remove the node_modules directory from the Git index manually.  I'm hoping then you will have a much cleaner commit. 

Sorry for the mess...

**Comment by justinlewis** [comment]
Actually,  no need for you do worry about the node_modules directory.  i just took care of it in your pull request.

**Comment by brendonakay** [comment]
I'll be available to make some updates later tonight if you would still like a cleaner commit.

**Comment by justinlewis** [comment]
Good work.  I found a couple small bugs where instance attributes weren't referenced with 'self' and where method calls had too many params but otherwise the update seems to work.  I commented out all the self.conn.close() methods because they where closing cursors before the cursors should be closed.  I didn't have time to look into un-commenting them but I pushed my changes back to your branch.  Can you take a look?

I'm also pushing the node_modules change so please verify that directory is excluded from your index.  It might be worth running a 'npm install' at that point to make sure your local node_modules is synced with your package.json.  

Thanks a bunch for your help!

**Comment by brendonakay** [comment]
Glad it checks out! Sorry for the bugs I was having issues with my local environment and tried running them through the Python interpreter to check for defects. I'll be home later tonight to run some tests/checks. Looking forward to more contributions :)

**Comment by brendonakay** [comment]
I think we need to move these `self.conn.close()` methods to Python's built in `__del__()` method. At work now but can take a look later. In [here](http://initd.org/psycopg/docs/connection.html) it says that close() won't be usable from that point forward so closing it in the `__init__()` method could be doing just that. More to come later.

**Comment by brendonakay** [comment]
[Here](http://initd.org/psycopg/articles/2013/04/07/psycopg-25-released/) they use Python's context manager operation `with`, which could also be a viable alternative to the deconstructor method.

**Comment by justinlewis** [comment]
Your recent commits adding the __del__ method functionality seems to work.  I did some basic testing and it all seems to behave as expected.  I'm going to merge this into dev.

**Comment by brendonakay** [comment]
woohoo!

**Pull request merged**
